### ISSUE TITLE
Option to block gateway expired state 2 

### ISSUE THREAD

**Issue by NickRHill** [JordanGreenies/btcz.in_cubecart#3]
The API will generate a state 2 result pingback if the gateway expires. Other gateways, for example, Worldpay and Paypal don't noticeably use this feature, so the state 2 has an undesired consequence of using an order state which I use for other purposes. It may be good if there is an option to allow only pingback state 5 (if appropriate) to be generated.  Failures or timeouts leave without a pingback.

**Comment by NickRHill** [comment]
If we don't want timeout pingbacks, since the shop may have an alternative order time-out policy set in  the admin, the default timeout for payments could be made much longer.

**Comment by JordanGreenies** [comment]
You can disable this by commenting out the if statement on line 122 of modules/gateway/Bitcoinz/gateway.class.php
