### ISSUE TITLE
Updated order doesn't update payment amount

### ISSUE THREAD

**Issue by NickRHill** [JordanGreenies/btcz.in_cubecart#4]
Generate order. Click through to payment with BitcoinZ. Go back, update order, click pay with BitcoinZ. The original order amount is shown. 

Desired behaviour: If a user goes back to update an order prior to paying, the payment gateway should update the total when called again.

**Comment by JordanGreenies** [comment]
Fixed with latest commit, if they change order price, a new gateway will be generated with correct amount.

**Comment by NickRHill** [comment]
Great. Thanks! I look forward to testing it.

**Comment by NickRHill** [comment]
For this to work, will status 2 need to be disabled? since if a gateway has already been created for that order, the pre-existing gateway for that order will time out thereby putting it in status 2 potentially before it can be put into status 5.

**Comment by JordanGreenies** [comment]
Not possible since the confirmation for cubecart isn't by pingback but by user request on the success page.
Payment will only succeed or expire if they have the gateway open (this is how other cubecart addons operate too).
