### ISSUE TITLE
Don't ask for customer email address and send confirmations to shop email address

### ISSUE THREAD

**Issue by NickRHill** [JordanGreenies/btcz.in_cubecart#5]
One less step for customers would be to not have to enter their email address. It doesn't appear to generate emails to customers anyway. Maybe that step can be eliminated?

Automatic sending emails to the shop email address as defined in the admin section would be useful on completion or failure.

**Comment by JordanGreenies** [comment]
Emails are needed for support incase a transaction goes wrong.
I will disable pingback to emails

**Comment by NickRHill** [comment]
In case of issue, then retailer will be first port of call for the customer. So any pertinent information should be sent to retailer. 

Communication need not be sent to customer by API since Cubecart will typically keep customer informed of payment accepted, etc.

**Comment by NickRHill** [comment]
The current version is still asking for customer's email address.  It's not apparent why, since 
1) Customers aren't receiving any emails
2) Retailer manages interaction with customer

**Comment by NickRHill** [comment]
Please reopen this bug.

**Comment by JordanGreenies** [comment]
Email is needed incase customer needs to contact BTCz.in, we can confirm identity for transaction.
Not an issue or bug
