### ISSUE TITLE
Partial order payments don't end up in merchant's BitcoinZ address. 

### ISSUE THREAD

**Issue by NickRHill** [JordanGreenies/btcz.in_cubecart#6]
Page requests 824.826 to t1UeTZ3sAQV9iCSiphfUSLTQW6vxjzik8Zk
send 181.2 to t1UeTZ3sAQV9iCSiphfUSLTQW6vxjzik8Zk
The 181.2  doesn't seem to find it's way to merchant's BTCz address.

**Comment by NickRHill** [comment]
If you need mroe info, DM me on slack.

**Comment by JordanGreenies** [comment]
Sorted this, partial payments will now get forward to the merchant with an email notifying that the buyer may need manual assistance / refund
