### ISSUE TITLE
BitcoinZ URL media format should be used to make payments easier

### ISSUE THREAD

**Issue by NickRHill** [JordanGreenies/btcz.in_cubecart#7]
The media format `<a href="bitcoinz:[bitcoinzaddress]">click here</a>` should be used so that users can click the address and have it automatically open in an application which supports Bitcoinz. 

This functionality is aupported in the copay and coinomi android wallets.

If it is possible to embed the value of the transaction in the media string, that would improve usability still further.

**Comment by JordanGreenies** [comment]
done
