### ISSUE TITLE
Overpayments don't find their way to retailer

### ISSUE THREAD

**Issue by NickRHill** [JordanGreenies/btcz.in_cubecart#8]
Create order for 229.139 BTCz
Customer pays 240 BTCz
Retailer receives 229.1389
Unknown address t1chBW5iSsgQ81Akya2WfWe1NYnVwoKacED receives 10.861

Expected behaviour: Retailer should always receive all the funds the customer pays less any transaction charges. The retailer is in the best position to refund any overpayment, or there may be an out-of-band agreement with the customer to send an overpayment.

**Comment by NickRHill** [comment]
I notice address t1chBW5iSsgQ81Akya2WfWe1NYnVwoKacED was the receiving address for the next transaction. So perhaps the wallets are consecutive in an HD wallet?

**Comment by JordanGreenies** [comment]
Any accidental over-payments and the customer will need to contact BTCz.in in order the restore the funds.
Which is why customer email is needed.

**Comment by NickRHill** [comment]
As noted, the overpayment may not be accidental.

**Comment by NickRHill** [comment]
On making a payment, the buyer is making a contractual arrangement with the seller. 

If the seller is asking the buyer to make a payment to a third party gateway, payments to that gateway result in completion and fulfilment of that contract. The gateway contract is therefore with the seller, not the buyer. 

The seller is therefore legally bound to resolve issues which arise from payment processing and to fulfil orders which have been paid for in good faith in the manner the seller prescribes.

To be clear, there is no need for the customer's email address to be collected by the gateway, All payments from the customer MUST go to the seller since the seller is the counterparty to the contract. Otherwise, you need to contract with the seller to hold onto payments. And why would a seller want or agree to that?

That is the law of contract. This is an established precedent in common law countries for hundreds of years. 

For me to recommend or use this system, the seller must receive any and all payments to addresses provided on the gateway less any agreed fees. 

Please re-open this bug.

**Comment by JordanGreenies** [comment]
Ok sorted, now we don't require any email and over payments should get sent to the merchant

**Comment by NickRHill** [comment]
Thanks :-)
