### ISSUE TITLE
When using mobile browser, payment gateway doesn't show

### ISSUE THREAD

**Issue by NickRHill** [JordanGreenies/btcz.in_cubecart#9]
Click on pay with BTCz at checkout. Taken to the next screen. On a desktop computer, I would be shown an entry box for email address.

On android, I see a frame as attached.

![btcs_checkout_android_prepped](https://user-images.githubusercontent.com/33939323/36632526-94b4a778-197f-11e8-9bd9-a212f36916af.png)

**Comment by JordanGreenies** [comment]
Ok ill take a look into this

**Comment by JordanGreenies** [comment]
Just tested this and it works as normal on a Mi MIX 2, what phone and browser are you using because it looks like it has an issue loading the javascript?

**Comment by JordanGreenies** [comment]
I've added a message for if javascript is disabled if that is the case

**Comment by NickRHill** [comment]
I have js enabled. I use a Jiayu S3 running android 4.4.4 
Standard browser. Has agent string 
"Mozilla/5.0 (Linux; Android 4.4.4; JY-S3 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36"

**Comment by JordanGreenies** [comment]
There has to be an error loading the JavaScript for that browser, does it have the capability of viewing debug info?
Also on the same phone see if it works on chrome.

**Comment by NickRHill** [comment]
Works with chrome agent string:
" "Mozilla/5.0 (Linux; Android 4.4.4; JY-S3 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36"

**Comment by JordanGreenies** [comment]
There is now a message for old browsers
